### ISSUE TITLE
Using just this module as a preset throws missing module error

### ISSUE THREAD

**Issue by abritinthebay** [rollup/babel-preset-es2015-rollup#16] opened 2016-09-19 05:56 UTC
Literally the only preset I have installed but I get this error (repeatedly)

`resolve failed:  { [Error: Cannot find module 'babel-plugin-object-rest-spread'] code: 'MODULE_NOT_FOUND' } babel-plugin-object-rest-spread`

Oddly, even IF I install that module it still throws that error.

**Comment by Rich-Harris** [comment] 2016-12-12 20:36
Sorry for the non-response – I suspect that was caused by an issue that is fixed in the latest version of this preset. Will close this issue as it's old, but shout if you still experience problems.

**Closed as completed by Rich-Harris** 2016-12-12 20:36 UTC
